version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    groups:
      patterns: ['nhsuk-frontend']
    schedule:
      interval: weekly

  - package-ecosystem: 'pip'
    directory: '/'
    groups:
      patterns: ['nhsuk-frontend-jinja']
    schedule:
      interval: weekly

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'daily'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'

    groups:
      docker:
        patterns:
          - 'docker/*'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'

    ignore:
      # nhsuk-frontend needs to be updated in conjunction with nhsuk-frontend-jinja
      - dependency-name: 'nhsuk-frontend'

    groups:
      build:
        patterns:
          - '@babel/*'
          - '@rollup/*'
          - 'rollup'
          - 'rollup-*'
          - 'sass-embedded'

      lint:
        patterns:
          - '@typescript-eslint/*'
          - 'eslint'
          - 'eslint-*'
          - 'prettier'
          - 'typescript'

      test:
        patterns:
          - '@testing-library/*'
          - 'babel-jest'
          - 'jest'
          - 'jest-*'

      tools:
        patterns:
          - 'concurrently'

  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'daily'

    ignore:
      # nhsuk-frontend-jinja needs to be updated in conjunction with nhsuk-frontend
      - dependency-name: nhsuk-frontend-jinja

    groups:
      frontend:
        patterns:
          - jinja2
          - whitenoise

      infra:
        patterns:
          - azure-identity
          - gunicorn
          - psycopg

      lint_and_test:
        patterns:
          - factory-boy
          - 'pytest*'
          - '*playwright*'
          - ruff
          - time-machine

      tools:
        patterns:
          - 'dotenv'
          - 'ipdb'

  - package-ecosystem: 'terraform'
    directory: '/'
    schedule:
      interval: 'daily'
