# Generated by Django 5.2.1 on 2025-06-03 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0011_recreate_participants_linkage"),
        ("participants", "0010_screeningepisode_appointment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="screeningepisode",
            name="participant",
        ),
        migrations.DeleteModel(
            name="Appointment",
        ),
        migrations.DeleteModel(
            name="ScreeningEpisode",
        ),
    ]
