# Generated by Django 5.2.3 on 2025-06-17 12:51

import uuid

import django.db.models.deletion
from django.db import migrations, models


def extract_status(apps, schema_editor):
    Clinic = apps.get_model("clinics", "Clinic")
    for clinic in Clinic.objects.all():
        clinic.statuses.create(state=clinic.state)


def revert_extract_status(apps, schema_editor):
    Clinic = apps.get_model("clinics", "Clinic")
    for clinic in Clinic.objects.all():
        clinic.state = clinic.statuses.first().state
        clinic.save()


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0012_remove_screeningepisode_participant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinic",
            name="state",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Scheduled"),
                    ("IN_PROGRESS", "In progress"),
                    ("CLOSED", "Closed"),
                    ("CANCELLED", "Cancelled"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ClinicStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("IN_PROGRESS", "In progress"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="statuses",
                        to="clinics.clinic",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RunPython(extract_status, revert_extract_status),
        migrations.RemoveField(
            model_name="clinic",
            name="state",
        ),
    ]
