# Generated by Django 5.2.1 on 2025-06-16 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0012_remove_screeningepisode_participant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinics.setting'),
        ),
        migrations.AlterField(
            model_name='clinicslot',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinic_slots', to='clinics.clinic'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinics.provider'),
        ),
    ]
