# Generated by Django 5.2.3 on 2025-06-20 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0013_alter_clinic_setting_alter_clinicslot_clinic_and_more'),
        ('clinics', '0013_move_clinic_state_to_table'),
    ]

    operations = [
    ]
