# Generated by Django 5.2.3 on 2025-06-26 14:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('alt_name', models.CharField(max_length=50)),
                ('holding_clinic', models.BooleanField()),
                ('location_code', models.CharField(max_length=50)),
                ('address_line_1', models.CharField(max_length=50)),
                ('address_line_2', models.CharField(max_length=50)),
                ('address_line_3', models.CharField(max_length=50)),
                ('address_line_4', models.CharField(max_length=50)),
                ('address_line_5', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MessageBatch',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notify_id', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('unscheduled', 'Unscheduled'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('failed', 'Failed')], default='unscheduled', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nbss_id', models.CharField(max_length=30)),
                ('nhs_number', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('booked_by', models.CharField(max_length=50)),
                ('cancelled_by', models.CharField(max_length=50)),
                ('number', models.IntegerField(default=1, null=True)),
                ('starts_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notifications.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notify_id', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_enrichment', 'Pending enrichment'), ('enriched', 'Enriched'), ('sending', 'Sending'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending_enrichment', max_length=50)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notifications.appointment')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='notifications.messagebatch')),
            ],
        ),
    ]
