# Generated by Django 5.2.1 on 2025-06-16 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog_system_update_id_alter_auditlog_actor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='changes',
            new_name='snapshot',
        ),
    ]
