# Generated by Django 5.2.1 on 2025-06-16 14:26

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_changes_auditlog_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='snapshot',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
