# Generated by Django 5.2.1 on 2025-06-03 13:04

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0011_recreate_participants_linkage"),
        ("participants", "0009_fix_participant_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScreeningEpisode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screening_episode_new",
                        to="participants.participant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CONFIRMED", "Confirmed"),
                            ("CANCELLED", "Cancelled"),
                            ("DID_NOT_ATTEND", "Did not attend"),
                            ("CHECKED_IN", "Checked in"),
                            ("SCREENED", "Screened"),
                            ("PARTIALLY_SCREENED", "Partially screened"),
                            ("ATTENDED_NOT_SCREENED", "Attended not screened"),
                        ],
                        default="CONFIRMED",
                        max_length=50,
                    ),
                ),
                ("reinvite", models.BooleanField(default=False)),
                ("stopped_reasons", models.JSONField(blank=True, null=True)),
                (
                    "clinic_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_appointment_set",
                        to="clinics.clinicslot",
                    ),
                ),
                (
                    "screening_episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="participants.screeningepisode",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunSQL(
            [
                """
                INSERT INTO
                    participants_screeningepisode(
                        id,
                        participant_id,
                        created_at,
                        updated_at
                    )
                SELECT
                    id,
                    participant_id,
                    created_at,
                    updated_at
                FROM
                    clinics_screeningepisode
                """,
                """
                INSERT INTO
                    participants_appointment(
                        id,
                        clinic_slot_id,
                        screening_episode_id,
                        created_at,
                        updated_at,
                        status,
                        reinvite,
                        stopped_reasons
                    )
                SELECT
                    id,
                    clinic_slot_id,
                    screening_episode_id,
                    created_at,
                    updated_at,
                    status,
                    reinvite,
                    stopped_reasons
                FROM
                    clinics_appointment
                """,
            ]
        ),
    ]
