# Generated by Django 5.2.1 on 2025-06-03 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0012_remove_screeningepisode_participant_and_more'),
        ('participants', '0010_screeningepisode_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='clinic_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.clinicslot'),
        ),
        migrations.AlterField(
            model_name='screeningepisode',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participants.participant'),
        ),
    ]
