# Generated by Django 5.2.1 on 2025-06-16 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0013_alter_clinic_setting_alter_clinicslot_clinic_and_more'),
        ('participants', '0011_alter_appointment_clinic_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='clinic_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinics.clinicslot'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='screening_episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='participants.screeningepisode'),
        ),
        migrations.AlterField(
            model_name='participantaddress',
            name='participant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='address', to='participants.participant'),
        ),
        migrations.AlterField(
            model_name='screeningepisode',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='participants.participant'),
        ),
    ]
