# Generated by Django 5.2.3 on 2025-06-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0013_move_appointment_status_to_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentstatus',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='participant',
            name='ethnic_group',
        ),
        migrations.AddField(
            model_name='participant',
            name='ethnic_background',
            field=models.CharField(blank=True, choices=[('english_welsh_scottish_ni_british', 'English, Welsh, Scottish, Northern Irish or British'), ('irish', 'Irish'), ('gypsy_or_irish_traveller', 'Gypsy or Irish Traveller'), ('any_other_white_background', 'Any other White background'), ('white_and_black_caribbean', 'White and Black Caribbean'), ('white_and_black_african', 'White and Black African'), ('white_and_asian', 'White and Asian'), ('any_other_mixed_or_multiple_ethnic_background', 'Any other mixed or multiple ethnic background'), ('indian', 'Indian'), ('pakistani', 'Pakistani'), ('bangladeshi', 'Bangladeshi'), ('chinese', 'Chinese'), ('any_other_asian_background', 'Any other Asian background'), ('african', 'African'), ('caribbean', 'Caribbean'), ('any_other_black_african_or_caribbean_background', 'Any other Black, African or Caribbean background'), ('arab', 'Arab'), ('any_other_ethnic_background', 'Any other ethnic group'), ('prefer_not_to_say', 'Prefer not to say')], null=True),
        ),
    ]
